import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Locales } from '@/shared/types';
import { defaultLocale } from '@/middleware';
import { Header } from '@/components/Layout/Header';

import '../styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locales };
}) {
  return (
    <html lang={params?.lang ?? defaultLocale}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
